// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful"
import { Document } from "@contentful/rich-text-types"

export interface IPageFields {
  /** Title */
  title: string

  /** Slug */
  slug: string

  /** Image */
  image?: Asset | undefined

  /** Description */
  description?: string | undefined

  /** SEO - Title */
  seo_title?: string | undefined

  /** SEO - Description */
  seo_description?: string | undefined

  /** SEO - URL (canonical) */
  seo_url?: string | undefined

  /** SEO - Image */
  seo_image?: Asset | undefined

  /** SEO - Keywords */
  seo_keywords?: string[] | undefined
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "page"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface IProductFields {
  /** Name */
  name: string

  /** Slug */
  slug: string

  /** Show on hompage */
  homepage: boolean

  /** Description */
  description?: string | undefined

  /** Main Image */
  mainImage: Asset

  /** Atmospheric Images */
  atmosphericImages?: Asset[] | undefined

  /** SEO - Title */
  seo_title?: string | undefined

  /** SEO - Description */
  seo_description?: string | undefined

  /** SEO - URL (canonical) */
  seo_url?: string | undefined

  /** SEO - Image */
  seo_image?: Asset | undefined

  /** SEO - Keywords */
  seo_keywords?: string[] | undefined
}

export interface IProduct extends Entry<IProductFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "product"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface ISiteMetadataFields {
  /** Company name */
  client_name: string

  /** Address */
  client_address?: string | undefined

  /** Zip code */
  client_zipCode?: string | undefined

  /** City */
  client_city?: string | undefined

  /** Phone number */
  client_phone?: string | undefined

  /** Email address */
  client_email: string

  /** Bank account */
  client_bankAccount?: string | undefined

  /** Opening hours */
  client_openingHours?: string | undefined

  /** Webshop */
  client_webshop?: string | undefined

  /** Social media - LinkedIn */
  client_socialMediaLinkedIn?: string | undefined

  /** Social media - Twitter */
  client_socialMediaTwitter?: string | undefined

  /** Social media - Facebook */
  client_socialMediaFacebook?: string | undefined

  /** Social media - Instagram */
  client_socialMediaInstagram?: string | undefined

  /** Social media - YouTube */
  client_socialMediaYouTube?: string | undefined

  /** SEO - Title */
  seo_title: string

  /** SEO - Description */
  seo_description: string

  /** SEO - URL */
  seo_url: string

  /** SEO - Image */
  seo_image?: Asset | undefined

  /** SEO - Keywords */
  seo_keywords?: string[] | undefined
}

export interface ISiteMetadata extends Entry<ISiteMetadataFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "siteMetadata"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export interface ISiteNavigationFields {
  /** Name */
  name: string

  /** Code */
  code?: string | undefined

  /** Page */
  page?: IPage | undefined

  /** Sub navigation */
  subNavItems?: ISiteNavigation[] | undefined
}

export interface ISiteNavigation extends Entry<ISiteNavigationFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: "siteNavigation"
        linkType: "ContentType"
        type: "Link"
      }
    }
  }
}

export type CONTENT_TYPE = "page" | "product" | "siteMetadata" | "siteNavigation"

export type LOCALE_CODE = "nl"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "nl"
