// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import type {
  ChainModifiers,
  Entry,
  EntryFieldTypes,
  EntrySkeletonType,
  LocaleCode,
} from "contentful"

export type CONTENT_TYPE = "page" | "product" | "siteMetadata" | "siteNavigation"

export type LOCALE_CODE = "nl"

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "nl"

export interface IPageFields {
  /** Title */
  title: EntryFieldTypes.Symbol

  /** Slug */
  slug: EntryFieldTypes.Symbol

  /** Image */
  image?: EntryFieldTypes.AssetLink | undefined

  /** Description */
  description?: EntryFieldTypes.RichText | undefined

  /** SEO - Title */
  seo_title?: EntryFieldTypes.Symbol | undefined

  /** SEO - Description */
  seo_description?: EntryFieldTypes.Text | undefined

  /** SEO - URL (canonical) */
  seo_url?: EntryFieldTypes.Symbol | undefined

  /** SEO - Image */
  seo_image?: EntryFieldTypes.AssetLink | undefined

  /** SEO - Keywords */
  seo_keywords?: EntryFieldTypes.Array<EntryFieldTypes.Symbol> | undefined
}

export type IPageSkeleton = EntrySkeletonType<IPageFields, "page">
export type IPageEntry<
  Modifiers extends ChainModifiers = undefined,
  Locales extends LocaleCode = LOCALE_CODE,
> = Entry<IPageSkeleton, Modifiers, Locales>

export interface IProductFields {
  /** Name */
  name: EntryFieldTypes.Symbol

  /** Slug */
  slug: EntryFieldTypes.Symbol

  /** Show on hompage */
  homepage: EntryFieldTypes.Boolean

  /** Description */
  description?: EntryFieldTypes.RichText | undefined

  /** Main Image */
  mainImage: EntryFieldTypes.AssetLink

  /** Atmospheric Images */
  atmosphericImages?: EntryFieldTypes.Array<EntryFieldTypes.AssetLink> | undefined

  /** SEO - Title */
  seo_title?: EntryFieldTypes.Symbol | undefined

  /** SEO - Description */
  seo_description?: EntryFieldTypes.Text | undefined

  /** SEO - URL (canonical) */
  seo_url?: EntryFieldTypes.Symbol | undefined

  /** SEO - Image */
  seo_image?: EntryFieldTypes.AssetLink | undefined

  /** SEO - Keywords */
  seo_keywords?: EntryFieldTypes.Array<EntryFieldTypes.Symbol> | undefined
}

export type IProductSkeleton = EntrySkeletonType<IProductFields, "product">
export type IProductEntry<
  Modifiers extends ChainModifiers = undefined,
  Locales extends LocaleCode = LOCALE_CODE,
> = Entry<IProductSkeleton, Modifiers, Locales>

export interface ISiteMetadataFields {
  /** Company name */
  client_name: EntryFieldTypes.Symbol

  /** Address */
  client_address?: EntryFieldTypes.Symbol | undefined

  /** Zip code */
  client_zipCode?: EntryFieldTypes.Symbol | undefined

  /** City */
  client_city?: EntryFieldTypes.Symbol | undefined

  /** Phone number */
  client_phone?: EntryFieldTypes.Symbol | undefined

  /** Email address */
  client_email: EntryFieldTypes.Symbol

  /** Bank account */
  client_bankAccount?: EntryFieldTypes.Symbol | undefined

  /** Opening hours */
  client_openingHours?: EntryFieldTypes.Text | undefined

  /** Webshop */
  client_webshop?: EntryFieldTypes.Symbol | undefined

  /** Social media - LinkedIn */
  client_socialMediaLinkedIn?: EntryFieldTypes.Symbol | undefined

  /** Social media - Twitter */
  client_socialMediaTwitter?: EntryFieldTypes.Symbol | undefined

  /** Social media - Facebook */
  client_socialMediaFacebook?: EntryFieldTypes.Symbol | undefined

  /** Social media - Instagram */
  client_socialMediaInstagram?: EntryFieldTypes.Symbol | undefined

  /** Social media - YouTube */
  client_socialMediaYouTube?: EntryFieldTypes.Symbol | undefined

  /** SEO - Title */
  seo_title: EntryFieldTypes.Symbol

  /** SEO - Description */
  seo_description: EntryFieldTypes.Text

  /** SEO - URL */
  seo_url: EntryFieldTypes.Symbol

  /** SEO - Image */
  seo_image?: EntryFieldTypes.AssetLink | undefined

  /** SEO - Keywords */
  seo_keywords?: EntryFieldTypes.Array<EntryFieldTypes.Symbol> | undefined
}

export type ISiteMetadataSkeleton = EntrySkeletonType<ISiteMetadataFields, "siteMetadata">
export type ISiteMetadataEntry<
  Modifiers extends ChainModifiers = undefined,
  Locales extends LocaleCode = LOCALE_CODE,
> = Entry<ISiteMetadataSkeleton, Modifiers, Locales>

export interface ISiteNavigationFields {
  /** Name */
  name: EntryFieldTypes.Symbol

  /** Code */
  code?: EntryFieldTypes.Symbol | undefined

  /** Page */
  page?: EntryFieldTypes.EntryLink<IPageSkeleton> | undefined

  /** Sub navigation */
  subNavItems?:
    | EntryFieldTypes.Array<EntryFieldTypes.EntryLink<ISiteNavigationSkeleton>>
    | undefined
}

export type ISiteNavigationSkeleton = EntrySkeletonType<ISiteNavigationFields, "siteNavigation">
export type ISiteNavigationEntry<
  Modifiers extends ChainModifiers = undefined,
  Locales extends LocaleCode = LOCALE_CODE,
> = Entry<ISiteNavigationSkeleton, Modifiers, Locales>
